if (annyang) {
    annyang.setLanguage('fi')
    annyang.debug(true);
    
  var commands = {
      'ruotsi': function() { sweden(); },
      'tanska': function() { denmark(); },
      'norja': function() { norway(); },
      'suomi': function() { finland(); },
      'viro': function() { estonia(); },
      'yhdistynyt kuningaskunta': function() { uk(); },
      'irlanti': function() { ireland(); },
      'france': function() { france(); },
      'alankomaat': function() { netherlands(); },
      'belgia': function() { belgium(); },
      'islanti': function() { iceland(); },
      'luxemburg': function() { luxembourg(); },
      'espanja': function() { spain(); },
      'portugali': function() { portugal(); },
      'andorra': function() { andorra(); },
      'färsaaret': function() { faroeislands(); },
      'grönlanti': function() { greenland(); },
      'kanada': function() { canada(); },
      'yhdysvallat': function() { usa(); },
      'bahama': function() { bahamas(); },
      'trinidad (ja tobago)': function() { trinidad(); },
      'peru': function() { peru(); },
      'uruguay': function() { uraguay(); },
      'argentiina': function() { argentina(); },
      'chile': function() { chile(); },
      'saksa': function() { germany(); },
      'sveitsi': function() { switzerland(); },
      'italia': function() { italy(); },
      'malta': function() { malta(); },
      'puola': function() { poland(); },
      'unkari': function() { hungary(); },
      'kypros': function() { cyprus(); },
      'australia': function() { australia(); },
      'uusi-seelanti': function() { newzealand(); },
      'japani': function() { japan(); },
      'moldova': function() { moldova(); },
      'romania': function() { romania(); },
      'etelä-afrikka': function() { southafrica(); },
      'lesotho': function() { lesotho(); },
      'swazimaa': function() { swaziland(); },
      'egypti': function() { egypt(); },
      'marokko': function() { morocco(); },
      'angola': function() { angola(); },
      'kenia': function() { kanya(); },
      'ruanda': function() { rwanda(); },
      'nigeria': function() { nigeria(); },
      'turkki': function() { turkey(); },
      'saudi arabia': function() { saudiarabia(); },
      'qatar': function() { qatar(); },
      'bahrain': function() { bahrain(); },
      'yhdistyneet arabiemiirikunnat': function() { uae(); },
      'israel': function() { israel(); },
      'itävalta': function() { austria(); },
      'san marino': function() { sanmarino(); },
      'vatikaanivaltio': function() { vatican(); },
      'venäjä': function() { russia(); },
      'tšekki': function() { czech(); },
      'uganda': function() { uganda(); },
      'venezuela': function() { venezuela(); },
      'tšad': function() { chad(); },
      'algeria': function() { algeria(); },
      'barbados': function() { barbados(); },
      'grenada': function() { grenada(); },
      'makedonia': function() { macedonia(); },
      'kosovo': function() { kosovo(); },
      'liettua': function() { lithuania(); },
      'latvia': function() { latvia(); },
      'valko-venäjä': function() { belarus(); },
      'ukraina': function() { ukraine(); },
      'slovakia': function() { slovakia(); },
      'albania': function() { albania(); },
      'bulgaria': function() { bulgaria(); },
      'montenegro': function() { montenegro(); },
      'kroatia': function() { croatia(); },
      'slovenia': function() { slovenia(); },
      'serbia': function() { serbia(); },
      'liechtenstein': function() { liechtenstein(); },
      'monaco': function() { monaco(); },
      'meksiko': function() { mexico(); },
      'honduras': function() { honduras(); },
      'el salvador': function() { elsalvador(); },
      'belize': function() { belize(); },
      'nicaragua': function() { nicaragua(); },
      'costa rica': function() { costarica(); },
      'panama': function() { panama(); },
      'kolumbia': function() { colombia(); },
      'venezuela': function() { venezuela(); },
      'ecuador': function() { ecuador(); },
      'guyana': function() { guyana(); },
      'suriname': function() { suriname(); },
      'brasilia': function() { brazil(); },
      'bolivia': function() { bolivia(); },
      'paraguay': function() { paraguay(); },
      'jamaika': function() { jamaica(); },
      'saint vincent (ja grenadiinit)': function() { saintvincent(); },
      'saint lucia': function() { saintlucia(); },
      'dominica': function() { dominica(); },
      'antigua (ja barbuda)': function() { antigua(); },
      'saint kitts (ja nevis)': function() { saintkitts(); },
      'dominikaaninen tasavalta': function() { dominicanrepublic(); },
      'haiti': function() { haiti(); },
      'kuuba': function() { cuba(); },
      'vanuatu': function() { vanuatu(); },
      'papua-uusi-guinea': function() { papua(); },
      'indonesia': function() { indonesia(); },
      'filippiinit': function() { philippines(); },
      'malesia': function() { malaysia(); },
      'singapore': function() { singapore(); },
      'brunei': function() { brunei(); },
      'etelä-korea': function() { southkorea(); },
      'pohjois-korea': function() { northkorea(); },
      'kiina': function() { china(); },
      'mongolia': function() { mongolia(); },
      'vietnam': function() { vietnam(); },
      'laos': function() { laos(); },
      'thaimaa': function() { thailand(); },
      'myanmar': function() { myanmar(); },
      'bhutan': function() { bhutan(); },
      'bangladesh': function() { bangaladesh(); },
      'intia': function() { india(); },
      'nepal': function() { nepal(); },
      'pakistan': function() { pakistan(); },
      'afghanistan': function() { afghanistan(); },
      'tadžikistan': function() { tajikistan(); },
      'turkmenistan': function() { turkmenistan(); },
      'uzbekistan': function() { uzbekistan(); },
      'kazakstan': function() { kazakhstan(); },
      'iran': function() { iran(); },
      'irak': function() { iraq(); },
      'syyria': function() { syria(); },
      'libanon': function() { lebanon(); },
      'jemen': function() { yemen(); },
      'oman': function() { oman(); },
      'armenia': function() { armenia(); },
      'azerbaidžan': function() { azerbaijan(); },
      'georgia': function() { georgia(); },
      'madagaskar': function() { madagascar(); },
      'mozambik': function() { mozambique(); },
      'malawi': function() { malawi(); },
      'zimbabwe': function() { zimbabwe(); },
      'sambia': function() { zambia(); },
      'botswana': function() { botswana(); },
      'namibia': function() { namibia(); },
      'kongon demokraattinen tasavalta': function() { democraticcongo(); },
      'kongon tasavalta': function() { republiccongo(); },
      'gabon': function() { gabon(); },
      'päiväntasaajan guinea': function() { equatorialguinea(); },
      'benin': function() { benin(); },
      'togo': function() { togo(); },
      'ghana': function() { ghana(); },
      'norsunluurannikko': function() { cotedivoire(); },
      'liberia': function() { liberia(); },
      'sierra leone': function() { sierraleone(); },
      'guinea': function() { guinea(); },
      'guinea bissau': function() { guineabissau(); },
      'gambia': function() { gambia(); },
      'senegal': function() { senegal(); },
      'mauritania': function() { mauritania(); },
      'libya': function() { libya(); },
      'niger': function() { niger(); },
      'mali': function() { mali(); },
      'burkina faso': function() { buerkinafaso(); },
      'kamerun': function() { cameroon(); },
      'burundi': function() { burundi(); },
      'tansania': function() { tanzania(); },
      'kenya': function() { kenya(); },
      'somalia': function() { somalia(); },
      'etiopia': function() { ethiopia(); },
      'eritrea': function() { eritrea(); },
      'djibouti': function() { djibouti(); },
      'keski-afrikan tasavalta': function() { car(); },
      'sudan': function() { sudan(); },
      'etelä-sudan': function() { southsudan(); },
      'mauritius': function() { mauritius(); },
      'komorit': function() { comoros(); },
      'kap verde': function() { capeverde(); },
      'são tomé ja príncipe': function() { saotome(); },
      'seychellit': function() { seychelles(); },
      'sri lanka': function() { srilanka(); },
      'fidži': function() { fiji(); },
      'tonga': function() { tonga(); },
      'samoa': function() { samoa(); },
      'tuvalu': function() { tuvalu(); },
  
  };

    annyang.addCommands(commands);
    annyang.start();
}