if (annyang) {
  annyang.setLanguage('pl')
  annyang.debug(true);
  
var commands = {
    'szwecja': function() { sweden(); },
    'dania': function() { denmark(); },
    'norwegia': function() { norway(); },
    'finlandia': function() { finland(); },
    'estonia': function() { estonia(); },
    'Wielka Brytania  ': function() { uk(); },
    'ireland': function() { ireland(); },
    'france': function() { france(); },
    '(the) netherlands': function() { netherlands(); },
    'belgium': function() { belgium(); },
    'iceland': function() { iceland(); },
    'luxembourg': function() { luxembourg(); },
    'spain': function() { spain(); },
    'portugal': function() { portugal(); },
    'andorra': function() { andorra(); },
    '(the) faroe islands': function() { faroeislands(); },
    'greenland': function() { greenland(); },
    'canada': function() { canada(); },
    '(the) united states': function() { usa(); },
    '(the) bahamas': function() { bahamas(); },
    'trinidad (and tobago)': function() { trinidad(); },
    'peru': function() { peru(); },
    'uruguay': function() { uraguay(); },
    'argentina': function() { argentina(); },
    'chile': function() { chile(); },
    'germany': function() { germany(); },
    'switzerland': function() { switzerland(); },
    'italy': function() { italy(); },
    'malta': function() { malta(); },
    'poland': function() { poland(); },
    'hungary': function() { hungary(); },
    'cyprus': function() { cyprus(); },
    'australia': function() { australia(); },
    'new zealand': function() { newzealand(); },
    'japan': function() { japan(); },
    'moldova': function() { moldova(); },
    'romania': function() { romania(); },
    'south africa': function() { southafrica(); },
    'lesotho': function() { lesotho(); },
    'swaziland': function() { swaziland(); },
    'egypt': function() { egypt(); },
    'morocco': function() { morocco(); },
    'angola': function() { angola(); },
    'kenya': function() { kanya(); },
    'rwanda': function() { rwanda(); },
    'nigeria': function() { nigeria(); },
    'turkey': function() { turkey(); },
    'saudi arabia': function() { saudiarabia(); },
    'qatar': function() { qatar(); },
    'bahrain': function() { bahrain(); },
    '(the) united arab emirates': function() { uae(); },
    'israel': function() { israel(); },
    'austria': function() { austria(); },
    'san marino': function() { sanmarino(); },
    '(the) vatican (city)': function() { vatican(); },
    'russia': function() { russia(); },
    'czech (republic)': function() { czech(); },
    'uganda': function() { uganda(); },
    'venezuela': function() { venezuela(); },
    'trinidad (and tobago)': function() { trinidad(); },
    'chad': function() { chad(); },
    'algeria': function() { algeria(); },
    'barbados': function() { barbados(); },
    'grenada': function() { grenada(); },
    '(north) macedonia': function() { macedonia(); },
    'kosovo': function() { kosovo(); },
    'lithuania': function() { lithuania(); },
    'latvia': function() { latvia(); },
    'belarus': function() { belarus(); },
    'ukraine': function() { ukraine(); },
    'slovakia': function() { slovakia(); },
    'albania': function() { albania(); },
    'bulgaria': function() { bulgaria(); },
    'montenegro': function() { montenegro(); },
    'croatia': function() { croatia(); },
    'slovenia': function() { slovenia(); },
    'serbia': function() { serbia(); },
    'liechtenstein': function() { liechtenstein(); },
    'monaco': function() { monaco(); },
    'mexico': function() { mexico(); },
    'honduras': function() { honduras(); },
    'el salvador': function() { elsalvador(); },
    'belize': function() { belize(); },
    'nicaragua': function() { nicaragua(); },
    'costa rica': function() { costarica(); },
    'panama': function() { panama(); },
    'colombia': function() { colombia(); },
    'venezuela': function() { venezuela(); },
    'ecuador': function() { ecuador(); },
    'guyana': function() { guyana(); },
    'suriname': function() { suriname(); },
    'brazil': function() { brazil(); },
    'bolivia': function() { bolivia(); },
    'paraguay': function() { paraguay(); },
    'jamaica': function() { jamaica(); },
    'saint vincent (and the grenadines)': function() { saintvincent(); },
    'saint lucia': function() { saintlucia(); },
    'dominica': function() { dominica(); },
    'antigua (and barbuda)': function() { antigua(); },
    'saint kitts (and nevis)': function() { saintkitts(); },
    'dominican republic': function() { dominicanrepublic(); },
    'haiti': function() { haiti(); },
    'cuba': function() { cuba(); },
    'vanuatu': function() { vanuatu(); },
    'papua new guinea': function() { papua(); },
    'indonesia': function() { indonesia(); },
    '(the) philippines': function() { philippines(); },
    'malaysia': function() { malaysia(); },
    'singapore': function() { singapore(); },
    'brunei': function() { brunei(); },
    '(south) korea': function() { southkorea(); },
    'north korea': function() { northkorea(); },
    'china': function() { china(); },
    'mongolia': function() { mongolia(); },
    'vietnam': function() { vietnam(); },
    'laos': function() { laos(); },
    'thailand': function() { thailand(); },
    'myanmar': function() { myanmar(); },
    'bhutan': function() { bhutan(); },
    'bangladesh': function() { bangaladesh(); },
    'india': function() { india(); },
    'nepal': function() { nepal(); },
    'pakistan': function() { pakistan(); },
    'afghanistan': function() { afghanistan(); },
    'tajikistan': function() { tajikistan(); },
    'turkmenistan': function() { turkmenistan(); },
    'uzbekistan': function() { uzbekistan(); },
    'kazakhstan': function() { kazakhstan(); },
    'iran': function() { iran(); },
    'iraq': function() { iraq(); },
    'syria': function() { syria(); },
    'lebanon': function() { lebanon(); },
    'yemen': function() { yemen(); },
    'oman': function() { oman(); },
    'armenia': function() { armenia(); },
    'azerbaijan': function() { azerbaijan(); },
    'georgia': function() { georgia(); },
    'madagascar': function() { madagascar(); },
    'mozambique': function() { mozambique(); },
    'malawi': function() { malawi(); },
    'zimbabwe': function() { zimbabwe(); },
    'zambia': function() { zambia(); },
    'botswana': function() { botswana(); },
    'namibia': function() { namibia(); },
    'democratic republic of the congo': function() { democraticcongo(); },
    'republic of the congo': function() { republiccongo(); },
    'gabon': function() { gabon(); },
    'equatorial guinea': function() { equatorialguinea(); },
    'benin': function() { benin(); },
    'togo': function() { togo(); },
    'ghana': function() { ghana(); },
    'cote d ivoire': function() { cotedivoire(); },
    'liberia': function() { liberia(); },
    'sierra leone': function() { sierraleone(); },
    'guinea': function() { guinea(); },
    'guinea bissau': function() { guineabissau(); },
    '(the) gambia': function() { gambia(); },
    'senegal': function() { senegal(); },
    'mauritania': function() { mauritania(); },
    'libya': function() { libya(); },
    'niger': function() { niger(); },
    'nigeria': function() { nigeria(); },
    'mali': function() { mali(); },
    'burkina faso': function() { burkinafaso(); },
    'cameroon': function() { cameroon(); },
    'burundi': function() { burundi(); },
    'tanzania': function() { tanzania(); },
    'kenya': function() { kenya(); },
    'somalia': function() { somalia(); },
    'ethiopia': function() { ethiopia(); },
    'eritrea': function() { eritrea(); },
    'djibouti': function() { djibouti(); },
    'central african republic': function() { car(); },
    'sudan': function() { sudan(); },
    'south sudan': function() { southsudan(); },
    'mauritius': function() { mauritius(); },
    'comoros': function() { comoros(); },
    'cape verde': function() { capeverde(); },
    'sao tome and principe': function() { saotome(); },
    'seychelles': function() { seychelles(); },
    'sri lanka': function() { srilanka(); },
    'fiji': function() { fiji(); },
    'tonga': function() { tonga(); },
    'samoa': function() { samoa(); },
    'tuvalu': function() { tuvalu(); },

};

  annyang.addCommands(commands);
  annyang.start();
}