if (annyang) {
    annyang.setLanguage('en-US')
    
  var commands = {
      'sweden': function() { sweden(); },
      'denmark': function() { denmark(); },
      'norway': function() { norway(); },
      'finland': function() { finland(); },
      'estonia': function() { estonia(); },
      '(the) united kingdom': function() { uk(); },
      'ireland': function() { ireland(); },
      'france': function() { france(); },
      '(the) netherlands': function() { netherlands(); },
      'belgium': function() { belgium(); },
      'iceland': function() { iceland(); },
      'luxembourg': function() { luxembourg(); },
      'spain': function() { spain(); },
      'portugal': function() { portugal(); },
      'andorra': function() { andorra(); },
      '(the) faroe islands': function() { faroeislands(); },
      'greenland': function() { greenland(); },
      'canada': function() { canada(); },
      '(the) united states': function() { usa(); },
      '(the) bahamas': function() { bahamas(); },
      'trinidad (and tobago)': function() { trinidad(); },
      'peru': function() { peru(); },
      'uruguay': function() { uraguay(); },
      'argentina': function() { argentina(); },
      'chile': function() { chile(); },
      'germany': function() { germany(); },
      'switzerland': function() { switzerland(); },
      'italy': function() { italy(); },
      'malta': function() { malta(); },
      'poland': function() { poland(); },
      'hungary': function() { hungary(); },
      'cyprus': function() { cyprus(); },
      'australia': function() { australia(); },
      'new zealand': function() { newzealand(); },
      'japan': function() { japan(); },
      'moldova': function() { moldova(); },
      'romania': function() { romania(); },
      'south africa': function() { southafrica(); },
      'lesotho': function() { lesotho(); },
      'swaziland': function() { swaziland(); },
      'egypt': function() { egypt(); },
      'morroco': function() { morocco(); },
      'angola': function() { angola(); },
      'kenya': function() { kanya(); },
      'rwanda': function() { rwanda(); },
      'nigeria': function() { nigeria(); },
      'turkey': function() { turkey(); },
      'saudi arabia': function() { saudiarabia(); },
      'qatar': function() { qatar(); },
      'bahrain': function() { bahrain(); },
      '(the) united arab emirates': function() { uae(); },
      'israel': function() { israel(); },
      'austria': function() { austria(); },
      'san marino': function() { sanmarino(); },
      '(the) vatican (city)': function() { vatican(); },
      'russia': function() { russia(); },
      'czech (republic)': function() { czech(); },
      'uganda': function() { uganda(); },
      'venezuela': function() { venezuela(); },
      'trinidad (and tobago)': function() { trinidad(); },
      'chad': function() { chad(); },
      'algeria': function() { algeria(); },
      'barbados': function() { barbados(); },
      'grenada': function() { barbados(); },
      'macedonia': function() { macedonia(); },
      'kosovo': function() { kosovo(); },
  };

    annyang.addCommands(commands);
    annyang.start();
}